name: 'Environment'

on: 
  push

permissions:
  contents: read

jobs:
  debug:
    name: 'Debug'
    runs-on: ubuntu-latest
    environment: staging_environment

    defaults:
      run:
        shell: bash

    steps:
    - name: Environment
      run: env | sort

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"